### ISSUE TITLE
waitForJobs

### ISSUE THREAD

**Issue by surmann** [mllg/batchtools#1]
I fixed some issues of `waitForJobs` in 7925170bfc2fff640c159a58f1ceff14f70db6d7. However, the progressbar hides before all jobs are done. A MWE will follow.

**Comment by mllg** [comment]
You need to store the number of currently running jobs in each iteration, compare with the number of jobs of the previous iteration and pass the difference to `pb$tick()`. This is a little cumbersome, we ideally want to use `pb$update()` (which is currently broken, see https://github.com/gaborcsardi/progress/pull/24).

**Comment by surmann** [comment]
The first test for `waitForJobs` fails currently on LiDO.

**Comment by mllg** [comment]
Should be fixed by now.
