### ISSUE TITLE
Slurm Template conditional lines

### ISSUE THREAD

**Issue by ja-thomas** [mllg/batchtools#108]
Might be a stupid question, but depending on the cluster I'm submitting I may or may not want to specify an additional partition argument.

```
...
#SBATCH --clusters=<%= resources$clusters %>
#SBATCH --partition=<%= resources$partition %>
...
```
So the second line can only be there if `resources$partition` is not null (there is no default partition argument that I can set). Is there a way to conditionally set slurm lines in the template file?

e.g.

```
<%
## set partition if required
if(!is.null(resources$partition){
paste("#SBATCH --partition=", resources$partition)
}
-%>
```
something like this? But that seems to be ignored by `cfBrewTemplate`

**Comment by berndbischl** [comment]
That's more or less a brew question.
Let me try later.

**Comment by berndbischl** [comment]
Hmm. Shouldnt your code just work? Are you REALLY sure that the partition slot is not always NULL and hence paste always fails and returns something empty as well?

**Comment by smilesun** [comment]
I just added this line to our template, 
`#SBATCH --partition=serial_large_mem`

but I got 
`sbatch: error: Batch job submission failed: Invalid partition name specified'`

**Comment by mllg** [comment]
```r
ee = new.env()
ee$resources = list(partition = "foo")

brew(text = '
<%=
## set partition if required
if(!is.null(resources$partition)) {
paste("#SBATCH --partition=", resources$partition)
}
-%>
'
, envir = ee)
```

The important part is the `<%=`.

**Comment by berndbischl** [comment]
> I just added this line to our template,
> #SBATCH --partition=serial_large_mem
> 
> but I got
> sbatch: error: Batch job submission failed: Invalid partition name specified'

thats LRZ related and has nothing to do with bt in general

**Comment by smilesun** [comment]
OK, then the lrz documentation is out dated!
`https://www.lrz.de/services/compute/linux-cluster/batch_serial/limits/`
serial_mpp2 do work

**Comment by berndbischl** [comment]
> OK, then the lrz documentation is out dated!
> https://www.lrz.de/services/compute/linux-cluster/batch_serial/limits/
> serial_mpp2 do work

might be. but this discussion then still does not belong im the batchtools tracker ;-)

**Comment by ja-thomas** [comment]
@mllg Thanks for helping, that works
