### ISSUE TITLE
reduceResults: is init suboptimal?

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#116]
how can i set the "init" arg, but avoid that the first object is not joined in again?

more concrete example:

say my jobs results are all lists. from the lists, i only want element "foo". 

my reduction function is something like
fun = function(aggr, r) mycombo(aggr, r$foo)

where "mycombo" joins 2 elements of class "Foo". Now what if for class "Foo" there is no "neutral" empty element?
I can surely set "init" to res1$foo. but if do that, batchtools will now join init AGAIN with res1 in the first loop.

I hope my example was not too confused to understand ....

EDIT: I guess in "ids" i just start at index 2? and i was too stupid to see this when i needed this?

@smilesun

**Comment by mllg** [comment]
The function was underdocumented. Everything clear after b8f23fe20b7e445e80093f97be4d49474cec0546?

**Comment by mllg** [comment]
Sometimes, you might need to write a small wrapper if your combine function does not support a neutral element natively:
```r
wrapper = function(x, y) if (is.null(x)) y else mycombine(x, y)
```

**Comment by berndbischl** [comment]
> The function was underdocumented. Everything clear after b8f23fe?

the doc changes look good, but i knew all of this before, and still couldnt figure it out

**Comment by berndbischl** [comment]
> Sometimes, you might need to write a small wrapper if your combine function does not support a neutral element natively:
> 
> wrapper = function(x, y) if (is.null(x)) y else mycombine(x, y)

i dont see how this example makes sense? why should x be NULL (during reduction)?

isnt my final comment that I should start with ids = 2 the best solution?

**Comment by mllg** [comment]
> i dont see how this example makes sense? why should x be NULL (during reduction)?
> 
> isnt my final comment that I should start with ids = 2 the best solution?

It is possible to start with the 2nd id. I would still prefer this:
```r
wrapper = function(x, y) if (is.null(x)) y$foo else mycombo(x, y$foo)
reduceResults(wrapper, ids, init = NULL)
```
Alternatives:
```r
tmp = reduceResultsList(ids, function(x) x$foo)
Reduce(mycombo, tmp) # mycombo not vectorized
do.call(mycombo, tmp) # mycombo vectorized
```

**Comment by berndbischl** [comment]
the alternative i know, thats what i showed to the student who needed this.

> why should x be NULL (during reduction)?

ok, because you set it in "init", in your fully posted example now. i have to admit i find this is a bit "contrived".

anyway, can we maybe add these options to the examples section of reduceResults? i think all options are informative solutions.

**Comment by berndbischl** [comment]
@Coorsaa
