### ISSUE TITLE
submitJobs(id = NULL) submits all

### ISSUE THREAD

**Issue by HeidiSeibold** [mllg/batchtools#119]
```
> bla <- NULL
> submitJobs(ids = bla)
Submitting 51846 jobs in 51846 chunks using cluster functions 'Multicore' ...`
```

Maybe not the most intuituve behaviour :)

**Comment by berndbischl** [comment]
but well-documented behavior.....

**Comment by berndbischl** [comment]
NULL is the default, which implieds ids = findNotSubmitted

**Comment by HeidiSeibold** [comment]
You're right. I just had a typo somewhere and this lead to me submitting all jobs, so I thought this may frustrate people.

You can just ignore it if you want and close :monkey:

**Comment by berndbischl** [comment]
changing the defaults is always a bit bad
lets wait what michel says

another option would be not submit nothing on NULL, thats more conservative (but changes behavior)

**Comment by berndbischl** [comment]
> I think it's fairly common to have NULL be the place holder to pass whenever you want to get the default behavior.

Thats the default in all of my projects now (because "missing()" in R is somewhat broken and bad)

**Comment by mllg** [comment]
I'll stick to `NULL` as default, `missing` is not working reliably. `integer(0)` and a zero-row data.frame can be used to express "no ids".
