### ISSUE TITLE
reduceResultsDataTable: allows list colums in result?

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#134]
is that possible? the docs say no.
but it should be no problem?

an example also would be nice

**Comment by mllg** [comment]
I will allow it in the next release, see also my comment in #133.

**Comment by berndbischl** [comment]
just to be sure that by setup is understood:

assume i have jobs, where a vector "y" is produced at the end.
y has different lengths.

i would like to collect this with reduceResultsDataTable.

The natural thing would be to put in into a single result col, also called "y". 
I must be of type "list" now, as each entry in a cell would be a numvec.

**Comment by mllg** [comment]
Yep, understood. You will get the result in a list (so that you can program on it whatever is in there). If you now want a vector, you call something like
```r
res = reduceResultsDataTable()
res = flatten(res)
```
to unnest the result column (if possible).

**Comment by berndbischl** [comment]
the flatten wouldn't really make sense here as I said the vecs have different lengths. 
I am happy if i can produce a list col (with any entries i like)

at the moment I am using reduceResultsList as a workaround, which is ok, just less "nice" for subsequent processing

**Comment by mllg** [comment]
`flatten`/`unnest` are around for some time now, closing.
