### ISSUE TITLE
ERROR:  Error in !"written" : invalid argument type

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#143]
I'll share the following just for the record in case someone else experience it as well.  

One of the CRAN servers reported the following error while testing examples during `R CMD check` for future.batchtools:
```r
    ### [bt 2017-09-15 20:14:47]: Setting working directory to '/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/future.batchtools.Rcheck'
    ### [bt 2017-09-15 20:14:47]: Memory measurement disabled
    ### [bt 2017-09-15 20:14:47]: Starting job [batchtools job.id=1]
    ### [bt 2017-09-15 20:14:48]: Job terminated successfully [batchtools job.id=1]
    Error in !"written" : invalid argument type
    Calls: <Anonymous> ... writeRDS -> saveRDS -> [ -> [.data.table -> eval -> eval
    Execution halted
```
It could be a hiccup, but since the error message such that `!"written"` was evaluated;
```r
> !"written"
Error in !"written" : invalid argument type
```
it looks like a programming error somewhere.  The error occurred just now and was not there the previous time this exact same version was tests on that machine.   It is the first time I've observed it, I'm not sure if it is related to batchtools per se, or an issue in one of the dependent packages (`data.table`?).  

# Full CRAN output

Server log: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/future.batchtools-00check.html) (will most likely show something different in a few days).

```r
Check: examples 
Result: ERROR 
    Running examples in ‘future.batchtools-Ex.R’ failed
    The error most likely occurred in:
    
    > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
    > ### Name: batchtools_local
    > ### Title: batchtools local and interactive futures
    > ### Aliases: batchtools_local batchtools_interactive
    > 
    > ### ** Examples
    > 
    > ## Use local batchtools futures
    > plan(batchtools_local)
    > 
    > ## A global variable
    > a <- 1
    > 
    > ## Create explicit future
    > f <- future({
    + b <- 3
    + c <- 2
    + a * b * c
    + })
    > v <- value(f)
    Warning in waitForJobs(ids = jobid, timeout = timeout, sleep = sleep_fcn, :
     Some jobs disappeared from the system
    Error: BatchtoolsExpiration: Future ('<none>') expired (registry path /home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/future.batchtools.Rcheck/.future/20170915_201447-DcFRlp/batchtools_570175513).. The last few lines of the logged output:
    ### [bt 2017-09-15 20:14:47]: Setting working directory to '/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/future.batchtools.Rcheck'
    ### [bt 2017-09-15 20:14:47]: Memory measurement disabled
    ### [bt 2017-09-15 20:14:47]: Starting job [batchtools job.id=1]
    ### [bt 2017-09-15 20:14:48]: Job terminated successfully [batchtools job.id=1]
    Error in !"written" : invalid argument type
    Calls: <Anonymous> ... writeRDS -> saveRDS -> [ -> [.data.table -> eval -> eval
    Execution halted
    Warning in delete.BatchtoolsFuture(future, onRunning = "skip", onMissing = "ignore", :
     Will not remove batchtools registry, because the status of the batchtools was ‘defined’, ‘expired’, ‘submitted’ and option 'future.delete' is FALSE or running in an interactive session: ‘/home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/future.batchtools.Rcheck/.future/20170915_201447-DcFRlp/batchtools_570175513’ 
```

**Comment by HenrikBengtsson** [comment]
Update: I doesn't look like this is a random hiccup, because the same error now appear on a second R-devel CRAN server; https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/future.batchtools-00check.html.  My bets are now that something changed in R-devel that causes this.

**Comment by HenrikBengtsson** [comment]
It looks like something is hitting the data.table package badly. Specifically, on https://cran.r-project.org/web/checks/check_results_data.table.html, is see:
```r
     Test 812 Error in !"b" : invalid argument type
     Test 814 didn't produce correct warning :
     > DT[, !"foo", with = FALSE] 
     Expected warning: 'column(s) not removed because not found: foo'
     Observed error: 'Error in !"foo" : invalid argument type'
```
which looks very related to the problem in this issue.

**Comment by mllg** [comment]
Thanks for reporting. I suspect ALTREPs (<https://svn.r-project.org/R/branches/ALTREP/ALTREP.html>) to be the problem here.

**Comment by HenrikBengtsson** [comment]
Both future.batchtools and data.table seem to have self-recovered from this on CRAN:

* https://cran.r-project.org/web/checks/check_results_future.batchtools.html
* https://cran.r-project.org/web/checks/check_results_data.table.html

So 99.9% likely a R-devel thing.

**Comment by Pathfinder22** [comment]
Similar Issue:
ERROR: Error in !"readOnly" : invalid argument type
Resolution:
readOnly=False;readOnlyOptimize=FALSE
Installed package SVN
check you working  directory with getwd()
make sure you are in the directory where the file is located

Should work.

Secondary errors: 
External table not in the expected format.

I was using a file path variable to store and route to the directory. Error pops up, when you are in the directory and trying to force a path to the directory again.
