### ISSUE TITLE
waitForJobs - some more granularity ? 

### ISSUE THREAD

**Issue by michaelmayer2** [mllg/batchtools#146]
I am really happy with batchtools and it does exactly what we need. Been using BatchJobs before and now moved to batchtools.

A small issue became apparen however lately to me:  I can see that the waitForJobs routine was already refactored and improved a lot I am wondering if I am doing something wrong or missing something:

My code is running a couple of tasks and they are starting to get scheduled and start running fine. Some of them however fail because they are killed by the scheduler (Elapsed Time Exceeded). There is nothing wrong with that for me. 

If WaitForJobs however detects such a situation (case 3 in waitForJobs repeat routine), it immediately fails and exits so that the remainder of the code continues. There it hits the registry cleanup which is bound to fails since there is still jobs running. 

I managed to hack a second repeat loop into case 3 that waits until there is no jobs in the queue any more and this seems to do the trick for us. 

Is there any other way to make sure all jobs are finished in waitForJobs irrespective if they are killed or finishing normally ?`

Many thanks,

Michael.

**Comment by mllg** [comment]
Michael,

I'm currently at a workshop but will look into this issue next week. 

Best,
Michel

**Comment by mllg** [comment]
I've introduced a new argument `stop.on.expire` in #147. Does this work for you?

**Comment by mllg** [comment]
This is now merged. Report back if you encounter any problems.

**Comment by michaelmayer2** [comment]
Works for me ! Thanks for fixing this. 

Michael.
