### ISSUE TITLE
Multicore with batchtools

### ISSUE THREAD

**Issue by PhilippPro** [mllg/batchtools#15]
Hi,

I tried to use `makeClusterFunctionsMulticore`. 

My registry looks like this:
```
regis = makeExperimentRegistry("probs-muell", 
                             packages = c("mlr", "OpenML"),
                             source = "/nfsmb/koll/probst/Random_Forest/RFParset/code/probst_defs.R",
                             work.dir = paste0(dir,"/results")
)
regis$cluster.functions = makeClusterFunctionsMulticore()
```

Then I try to submit it (after algorithm setting, etc)
```
ids = getJobTable()$job.id
ids = chunkIds(ids, chunk.size = 30)
submitJobs(ids)
```

`getStatus()` gives me following (also after waiting more time):

```
getStatus()
Status for 240 jobs:
  Submitted: 240 (100.0%)
  Queued   :   0 (  0.0%)
  Started  :   0 (  0.0%)
  Running  :   0 (  0.0%)
  Done     :   0 (  0.0%)
  Error    :   0 (  0.0%)
```
I do not find anything done in my results folder. 
What is wrong here?

**Comment by berndbischl** [comment]
hi, 

you need to seed debug = TRUE and send us the output

**Comment by berndbischl** [comment]
and the results folder is complete? all stuff there?

**Comment by PhilippPro** [comment]
debug = TRUE where? 

In my results folder is the "probs-muell" folder after setting the registry (with all the relevant content). 

What works: Not setting anything for `regis$cluster.functions` and then
`submitJobs(ids, resources = list(chunk.ncpus = 8))`

**Comment by berndbischl** [comment]
https://mllg.github.io/batchtools/vignettes/Setup.html

https://mllg.github.io/batchtools/Registry.html

**Comment by berndbischl** [comment]
> and the results folder is complete? all stuff there?

sorry, i misread your first post. you said NOTHING is in your results folder.

**Comment by PhilippPro** [comment]
In my folder "probs-muell" in "/nfsmb/koll/probst/Random_Forest/RFParset/results/" there are all the usual folders algorithms, jobs, logs, problems which are not empty, and also a results folder which remains empty after submitting.

**Comment by PhilippPro** [comment]
debug = TRUE does not provide any informations.

**Comment by berndbischl** [comment]
apparently the debugging is not perfect yet here. leave the debug in the reg, but also do this

makeClusterFunctionsMulticore(debug = TRUE)

what happens now?

**Comment by PhilippPro** [comment]
This:
```
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper list-jobs probs-muell
OS result (exit code 0):
character(0)
Submitting 300 jobs in 4 chunks using cluster functions 'Multicore' ...
Submitting [-------------------------------------------------------------------------------------------------------------------------]   0% eta:  ?s
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper status
OS result (exit code 0):
[1] "1.03 0 0 0"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper start-job /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/jobs/a5c47c75fd95096f57b7e215b22ff171.rds /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/logs/a5c47c75fd95096f57b7e215b22ff171.log
OS result (exit code 0):
[1] "6604"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper status
OS result (exit code 0):
[1] "1.03 1 0 1"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper start-job /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/jobs/a986a1e9a96bc5a7802972c8d530e8c6.rds /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/logs/a986a1e9a96bc5a7802972c8d530e8c6.log
OS result (exit code 0):
[1] "6625"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper status
OS result (exit code 0):
[1] "1.03 2 0 2"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper start-job /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/jobs/60e5515cd52d12e09fe6d4538c534450.rds /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/logs/60e5515cd52d12e09fe6d4538c534450.log
OS result (exit code 0):
[1] "6646"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper status
OS result (exit code 0):
[1] "1.03 3 0 3"
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper start-job /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/jobs/87f23bb709f4d3dcd004618ea550beea.rds /nfsmb/koll/probst/Random_Forest/RFParset/results/probs-muell/logs/87f23bb709f4d3dcd004618ea550beea.log
OS result (exit code 0):
[1] "6667"
                     
```

**Comment by berndbischl** [comment]
ok. this looks like jobs are spawned as the process id is returned. and the system can also be queried for resources. 

can you try to run a simple example with multicore where you only compute x+1 in your function f?
does that work?

**Comment by PhilippPro** [comment]
Ok, I made a minimal example (see below) and I know which point was crucial -> The "source" file.
The source file needed "dir" for loading datasets, but it was not available in the source code, when it was distributed to several cpus. Thanks for the help. Can be closed. 

```
library(mlr)
library(batchtools)
library(plyr)

dir = "/home/probst/Random_Forest/RFParset"
setwd(paste0(dir,"/results"))


unlink("probs-test", recursive = TRUE)
regis = makeExperimentRegistry("probs-test", 
                               packages = c("mlr", "OpenML"),
                               source = "/home/probst/Random_Forest/RFParset/code/probst_defs.R",
                               work.dir = paste0("/nfsmb/koll/probst/Random_Forest/RFParset","/results")
)

regis$cluster.functions = makeClusterFunctionsMulticore(debug = TRUE) # does not work

addProblem(name = as.character(1), data = 1)
# add one generic 'algo' that evals the RF in hyperpar space
addAlgorithm("eval", fun = function(job, data, instance, ...) {
  x = list(...)
data + x$x + 1
})

set.seed(124)
ades = data.frame(c(sample(1:100)))
names(ades) = "x"

addExperiments(algo.designs = list(eval = ades))

ids = getJobTable()$job.id
ids = chunkIds(ids, chunk.size = 10)
submitJobs(ids)
getStatus()

```

**Comment by PhilippPro** [comment]
Ok, now there is a new error in the multicore version.

If I add `lrn = makeLearner("classif.randomForest")` in the addAlgorithm I get following error:

```
 job.id terminated error                                                  message
  1:      1       TRUE  TRUE Error in FUN(X[[i]], ...) : could not find function "is"
```

**Comment by berndbischl** [comment]
well, this is due to the fact that @mllg now uses RScript to start rjobs on the slaves. 
And RScript does not load "methods". add "methods" to the packages in your registry. does that help?

**Comment by berndbischl** [comment]
> The source file needed "dir" for loading datasets, but it was not available in the source code, when it was distributed to several cpus

well. did batchtools show you you an error message? because it should have? 
can you try better explain with an example what really went wrong and how you figured this out? 
because to me it looked like bt did not produce the correct errmsg

**Comment by PhilippPro** [comment]
> well, this is due to the fact that @mllg now uses RScript to start rjobs on the slaves.
And RScript does not load "methods". add "methods" to the packages in your registry. does that help?

Yes it helps.

> well. did batchtools show you you an error message? because it should have?
can you try better explain with an example what really went wrong and how you figured this out?
because to me it looked like bt did not produce the correct errmsg

No there was no error message. I discovered it myself, by removing the source line in the minimal example code and executing it, so I saw that it has to be something in the source code, that doesn't work.

**Comment by berndbischl** [comment]
The latter then seems to be a bug in bt. This needs to show up as a job error in getStatus.

Does this only happen in multicore?

Please post a minimal example for this in another issue, maybe only with batchMap and close this here.

**Comment by PhilippPro** [comment]
It does not happen in interactive.

**Comment by mllg** [comment]
Side note: to enable debugging, you now have to set the option `batchtools.verbose` to `TRUE`. The other debug flags are not supported anymore.
