### ISSUE TITLE
Store a backup of registry.rds

### ISSUE THREAD

**Issue by jakob-r** [mllg/batchtools#154]
So that if the file is corrupted you can come back to the backup

**Comment by mllg** [comment]
There typically already is a backup if something went wrong while writing the registry (<https://github.com/mllg/batchtools/blob/master/R/saveRegistry.R>). Thoughts?

**Comment by jakob-r** [comment]
I think in the case the "registry.new.Rds" existed but was 0kb. 

So what is happening?
1. registry.new.Rds will be removed (probably not existent)
2. registry.new.Rds will be written
3. renaming registry.new.Rds -> registry.Rds (this apparently overwrites registry.Rds without warning)

What can go wrong?
1. Nothing
2. Corrupt file written? Probably/hopefully not possible
3. It [looks like](https://github.com/wch/r-source/blob/d259f8c9ce9b33c963b87a188ec94ca19e557bb2/src/main/platform.c#L748) when the renaming fails only a warning is issued and FALSE is returned. You probably want to throw an error if renaming fails [here](https://github.com/mllg/batchtools/blob/636b2b8a526f3162d0d1b937157c3053718e3fd2/R/saveRegistry.R#L27). Now the question is: Can `file.rename` destroy the `from` and the `to` at the same time?

How I would do it:
1. write "registry.Rds" and overwrite it
2. remove "registry.old.Rds" if it exists
3. copy "registry.Rds" to "registry.old.Rds"

**Comment by mllg** [comment]
This issue came up because the file system quota was exhausted. Maybe the `file.rename()` operation failed here for some reasons. This is very hard to reproduce.

Your proposed solution would require an extra copy of the registry. This could slow things down. I'll wait if others have problems, too. Never experienced this myself.

**Comment by jakob-r** [comment]
At least you should `stop()` if the result of `file.rename()` is not TRUE.

**Comment by mllg** [comment]
Ok this in now in the master. However, there is no real way to deal with this.
