### ISSUE TITLE
Question: Example for using batch system

### ISSUE THREAD

**Issue by pekosro** [mllg/batchtools#161]
Hi,
I'm looking for some example to submit a number of jobs to  an existing openlava(or LSF) queue.
All nodes seeing the same file system.
What has to be done ?

**Comment by mllg** [comment]
Did you try to follow the setup instructions in the vignette <https://mllg.github.io/batchtools/articles/batchtools.html>? You need to create (a) a config file which calls `makeClusterFunctionsOpenLava()` and (b) write a template file (or adjust an existing one to your needs).
