### ISSUE TITLE
Reuse Resources

### ISSUE THREAD

**Issue by surmann** [mllg/batchtools#164]
Is it possible to reuse the resources (walltime, memory) set in a job?

Yesterday, LiDo crashes. I want to submit my jobs with different resources again. Unfortunately, it is not possible to use a simple `submitJobs(findExpired())`, because the resources aren't reused.
What do you think about this feature?

**Comment by jakob-r** [comment]
+1 for having resources connected with a job

**Comment by mllg** [comment]
Will be covered via #174.
