### ISSUE TITLE
No Error message, when src file does not work. 

### ISSUE THREAD

**Issue by PhilippPro** [mllg/batchtools#17]
See #15 
The source file should contain something like 
`setwd(dir)`

Your main file
```
library(batchtools)
library(plyr)

dir = "/home/probst/Random_Forest/RFParset"
setwd(paste0(dir,"/results"))

unlink("probs-test", recursive = TRUE)
regis = makeExperimentRegistry("probs-test", 
                               source = "/home/probst/Random_Forest/RFParset/code/probst_defs.R"
)

regis$cluster.functions = makeClusterFunctionsMulticore(debug = TRUE)

addProblem(name = as.character(1), data = 1)

addAlgorithm("eval", fun = function(job, data, instance, ...) {
  x = list(...)
  data + x$x + 1
})

set.seed(124)
ades = data.frame(c(sample(1:100)))
names(ades) = "x"

addExperiments(algo.designs = list(eval = ades))

ids = getJobTable()$job.id
ids = chunkIds(ids, chunk.size = 10)
submitJobs(ids)
getStatus()
```
Result: 
```
OS cmd: /nfsmb/koll/probst/R/x86_64-pc-linux-gnu-library/3.2/batchtools/bin/linux-helper list-jobs probs-test
OS result (exit code 0):
character(0)
Status for 100 jobs:
  Submitted: 100 (100.0%)
  Queued   :   0 (  0.0%)
  Started  :   0 (  0.0%)
  Running  :   0 (  0.0%)
  Done     :   0 (  0.0%)
  Error    :   0 (  0.0%)
```

**Comment by mllg** [comment]
Do you have a log file? Does `showLog(1)` help to spot the error?

**Comment by PhilippPro** [comment]
Yes this helps. Result of `showLog(1)`:

```
[job(chunk): 2016-05-25 14:18:17] Starting calculation of 10 jobs
[job(chunk): 2016-05-25 14:18:17] Setting working directory to '/nfsmb/koll/probst/Random_Forest/RFParset/results'
Error in setwd(dir) : character argument expected
Calls: <Anonymous> ... loadRegistryDependencies -> lapply -> FUN -> eval -> eval -> setwd
Execution halted
                     
```

**Comment by berndbischl** [comment]
@PhilippPro 
Can you please debug this on your machine a bit? is the encoding wrong here or what?

**Comment by mllg** [comment]
This is just a failed variable lookup in a user script which is sourced on the slave before the job starts. I think I can fix this to be better visible for the user. Not high priority though, log output is already pretty precise.

**Comment by berndbischl** [comment]
so what happens is: 
the user adds a source file to the reg, which contains an error?

**Comment by mllg** [comment]
Yes. And it does not pop up on the master because the variable is defined in the global env.

**Comment by berndbischl** [comment]
ok thx. still, we should try-catch all errors that occur when sourcing these files? 
i mean, the source files usually contain "library"  function code, so that could be the "bulk" of the code that in the end gets executed on the slave.

and if an error happens, getStatus should show that.

(the things with the master / globalenv is just unfortunate, and bad luck, and i would not invest work to fix that)
