### ISSUE TITLE
how to specify queue on SGE?

### ISSUE THREAD

**Issue by tikacp** [mllg/batchtools#185]
hi,

i just cannot figure out how to specify which queue to use on a SGE.
i also cannot find any mentioning of this in the documentation.
can somebody please help me out here? if i don't specify a queue i run into:

```
Error in submitJobs(resources = list(walltime = 3600, memory = 1024)) : 
  Fatal error occurred: 101. Command 'qsub' produced exit code 2. Output: 'Unable to read script file because of error: ERROR! -q option must have queue list argument'

```

cheers
tim

**Comment by mllg** [comment]
You have two options:

1. You specify the queue as a resource:
    ```r
    submitJobs(resources = list(queue = "<queue-name>", walltime = 300, memory = 500)
    ```
    Your template file must then include a line like this: <https://github.com/mllg/batchtools/blob/master/inst/templates/sge-simple.tmpl#L20>

2. You use the other resources like walltime or memory to determine the queue which fits best. May not be possible on your system. Here is an example for a cluster in Dortmund: <https://github.com/mllg/batchtools/blob/master/inst/templates/slurm-lido3.tmpl#L19>.
    This example is for Slurm, but I hope you get the idea.

**Comment by tikacp** [comment]
that does the trick!
i just didn't get the connection between the submitJobs resources arg and the template file -q flag.
(btw, i now hardcoded the queue in my template file since this is more convenient in our setup.)

thanks for the quick reply!
