### ISSUE TITLE
Suggestion: allow a custom "Rscript" command in templates

### ISSUE THREAD

**Issue by jgrn307** [mllg/batchtools#189]
We have to use R/RScript via a singularity container, so we have to append:

singularity exec /some/simg RScript

I can (and have) tweaked the template file to do this, but would you consider adding in a parameter to allow custom RScript calls?

**Comment by mllg** [comment]
What would be the benefit if this would be a parameter? And a parameter to which function?

**Comment by jgrn307** [comment]
So it could be passed to a brew template -- not sure where, exactly, it would live?  Maybe as a "resource" to a cluster?

**Comment by jgrn307** [comment]
Second use case: sometimes in SLURM systems you may want to run Rscript via srun, e.g. 
`srun --exclusive Rscript [stuff]
`

**Comment by mllg** [comment]
You can already do stuff like this with templating:
```r
# provide command as resource
submitJobs(resources = list(rscript = "srun --exclusive Rscript -e"))

# last line in template
<%= resources$rscript %> 'batchtools::doJobCollection("<%= uri %>")'
```

**Comment by jgrn307** [comment]
Perfect!  That's all I needed!
