### ISSUE TITLE
makeRegistry and makeExperimentRegistry use different defaults for conf.file 

### ISSUE THREAD

**Issue by ja-thomas** [mllg/batchtools#19]
Hi,

`makeRegistry` and `makeExperimentRegistry` have two different defaults for `conf.file`

`makeRegistry = function(file.dir = "registry", work.dir = getwd(), conf.file = "~/.batchtools.conf.R", ...)`

`makeExperimentRegistry = function(file.dir = "registry", work.dir = getwd(), conf.file ="~/.batchtools.conf.r",...)`
 
(Just the difference between .R and .r)

I don't think this is intended?

**Comment by surmann** [comment]
Resolved
