### ISSUE TITLE
Allow warnings to be treated as warnings only, not errors

### ISSUE THREAD

**Issue by nosarcasm** [mllg/batchtools#193]
Currently cannot treat warnings as warnings, even when setting options(warn=1).

**Comment by mllg** [comment]
I cannot follow. I have a test for this where the warning is treated as a regular warning. Can you provide an example where you encounter problems or give some additional information?

**Comment by mllg** [comment]
Possibly related to #195, closing. Re-open if you still encounter problems with the devel release of withr.
