### ISSUE TITLE
Jobs with calls to withr::with_options(NULL, ...) crash

### ISSUE THREAD

**Issue by renozao** [mllg/batchtools#195]
Here is a minimal example:
```R
library(batchtools)
reg <- makeExperimentRegistry(file.dir = NA)
addProblem(name = "pb", data = 1)
algo <- function(data, job, instance, ...){
  print("start")
  withr::with_options(NULL, {print("in with_options")})
  print("done")
  10
  
}
addAlgorithm(name = "algo", fun = algo)
addExperiments(prob.designs = NULL, algo.designs = NULL)

# a direct call to the function works 
algo()

# when run as a job it breaks
testJob(id = 1)
```

The error thrown is:
```
Error in (function (...)  : invalid value for 'error'
15: (function (e) 
    traceback(2L))()
14: (function (...) 
    .Internal(options(...)))(add.smooth = TRUE, ambiguousMethodSelection = function (cond) 
```

Replacing `NULL` by `list(a = 1)` in the call to `withr::with_options` does not throw the error, and the code works as expected.

I am under Ubuntu but the same behavior happens under Windows.
Package versions are:
```
batchtools       0.9.8      2017-12-15 CRAN (R 3.4.2)
withr            2.1.2      2018-03-15 CRAN (R 3.4.4)
```

**Comment by mllg** [comment]
This is related to https://github.com/r-lib/withr/issues/73, right? I'll give @jimhester some more time to deal with this upstream before implementing workarounds here.

**Comment by renozao** [comment]
Possibly yes. I imagine that having `options = NULL` here is also a bit a of an edge case.
I'll await for a fix for r-lib/withr#73 and see. 
Can you please also update this thread once you tested the fix?
Thanks

**Comment by mllg** [comment]
> Can you please also update this thread once you tested the fix?

Sure.

**Comment by mllg** [comment]
This problem has been fixed upstream, your reprex works now. Let me know if you encounter any further issues.
