### ISSUE TITLE
LiDO3 error

### ISSUE THREAD

**Issue by surmann** [mllg/batchtools#199]
I got this error today on LiDO3 after submitting ~2k jobs in ~1k chunks.

    Error: Fatal error occurred: 101. Command 'sbatch' produced exit code 1. Output: 'sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)'

Any thoughts? Is it possible to handle this directly via batchtools?

**Comment by mllg** [comment]
Don't know what the problem is here. Did you submit an infeasible job or did you just reach your limit? Can this be treated like a temporary error, i.e. will this go away automatically after some time?

**Comment by mllg** [comment]
AFAICT, this is not a temporary error, so there is no apparent solution.
