### ISSUE TITLE
problem and algorithm in getJobPars as factors?

### ISSUE THREAD

**Issue by surmann** [mllg/batchtools#2]
Currently `problem` and `algorithm` are returned as characters, whereas nominal parameters are stored as factors in the result of `getJobPars`. This results in problems for statistical methods like ranger. Here `data.matrix(data)` is used which return NA on character columns.
Does it make sense to store everything by default as factors?

**Comment by mllg** [comment]
Problems and algorithms are now stored as factor internally. Therefore you should now always get factors in `getJob*`.
