### ISSUE TITLE
capital letter in conf file required

### ISSUE THREAD

**Issue by surmann** [mllg/batchtools#20]
We need a capital R in the conf file on LiDO. `~/.batchtools.conf.r` is not used, only `~/.batchtools.conf.R` switches to Torque. Do we intend this?
I needed an hour to find this issue...

Additional info:
`ExperimentRegistry.R` uses `.batchtools.conf.r`, `Registry.R` uses `.batchtools.conf.R`. I switch the first one to `R`.

**Comment by ja-thomas** [comment]
This is the same as #19

**Comment by mllg** [comment]
Dirk fixed this! Thanks!

**Comment by surmann** [comment]
As a convention we decided to use always capital `R` in file endings.
