### ISSUE TITLE
setJobFunction

### ISSUE THREAD

**Issue by dajmcdon** [mllg/batchtools#207]
In the old BatchTools version described in the JSS paper, there was a `setJobFunction()` which was good for fixing buggy code. Does `batchtools` have an analogue? Similarly, if, for instance, the algorithms (or a subset thereof) depend on an `R` package, and the package gets updated, can you rebind to the new package, and rerun the experiments without regenerating the problem instances?

**Comment by mllg** [comment]
> In the old BatchTools version described in the JSS paper, there was a `setJobFunction()` which was good for fixing buggy code. Does `batchtools` have an analogue?

I will re-implement something like this. Possibly together with #209.



> Similarly, if, for instance, the algorithms (or a subset thereof) depend on an `R` package, and the package gets updated, can you rebind to the new package, and rerun the experiments without regenerating the problem instances?

If you've added your problem with `cache = TRUE`, the instances are already cached on the file system. A package upgrade does not invalidate this cache. Simply re-running the respective experiments should pick up the previously computed instance, load the upgraded package and use it for the remaining part of the computation.
