### ISSUE TITLE
portability of registries

### ISSUE THREAD

**Issue by smilesun** [mllg/batchtools#215]
the code can be evolved rapidly over time, now there is a coupling between the evolved code and the registry, once code updated, one could port the registry to another computer, but the registry has unfinished jobs, that can not be run again, because it could not find those changed functions anymore.  Is there a way to fix this?

**Comment by mllg** [comment]
I don't get what you mean be evolved functions.

Generally it is possible to port a registry to another site to resume calculation there and keep your old jobs. The functions/algorithms are stored inside the registry, but only the last version. If you care about reproducibility, you should not overwrite these functions in a non trivial way.

**Comment by mllg** [comment]
Re-open and provide more details if something is still unclear.
