### ISSUE TITLE
reduceResultsDataTable

### ISSUE THREAD

**Issue by PhilippPro** [mllg/batchtools#22]
I am getting my results with 
`
reduceResultsDataTable(ids = ids_classif, fun = function(r) as.data.frame(as.list(r)), reg = regis, fill = TRUE)`

and it takes about 5 hours (50000 jobs). Is there a way to make it faster, maybe parallelizable?

**Comment by mllg** [comment]
If IO is the bottleneck, parallelization will not help. You could try to move the files to a SSD first.


As you are not performing any CPU heavy operations on the files, I don't think parallelization will get you much. But you can try:
```{r}
ncpus = 2
ids = chunkIds(findDone(), n.chunks = ncpus)
res = rbindlist(mclapply(split(ids$job.id, ids$chunk), reduceResultsDataTable, fill = TRUE), fill = TRUE)
setkeyv(res, "job.id")
```

Maybe you just convert too much, `as.list(r)` should be sufficient for most data types or you could maybe don't specify a function at all. However, I can only guess here, this depends on your result files.

Let me know if you have found a working solution. You can also send me the registry and I can have a closer look.

**Comment by berndbischl** [comment]
> If IO is the bottleneck, parallelization will not help.

so you are saying that these 2 things -  which where in BE, exactly for the purpose talked about here, in reduceResultsExperimentsParallel - do NOT help at all here

- chunking with block
- parallel reduction

?

I really cannot believe this? Have you ever tried this?

**Comment by berndbischl** [comment]
@PhilippPro 

Please also tell us (no details but roughly) 

- what is in a single job result
- data structure
- file size

**Comment by PhilippPro** [comment]
For each job: A named vector (obtained by performance). 

File size: 500 MB

Examples:
```
loadResult(id = c(12))
             acc              ber             mmce  multiclass.au1u multiclass.brier          logloss        timetrain 
       0.6666667        0.4613095        0.3333333        0.8885582        0.4315495        0.7139409        0.0960000 

```
```
> reduceResultsDataTable(ids = c(12,65), fun = function(r) as.data.frame(as.list(r)), reg = regis, fill = TRUE)
   job.id       acc       ber      mmce multiclass.au1u multiclass.brier   logloss timetrain                                                              
1:     12 0.6666667 0.4613095 0.3333333       0.8885582        0.4315495 0.7139409     0.096
2:     65 0.7407407 0.4047619 0.2592593       0.9036045        0.4082344 0.7346146     0.518
```

**Comment by berndbischl** [comment]
> File size of the whole: ~350 MB

you mean the whole registry? (which is not a file but a dir....)
so each result itself is just a tiny num vector, with 5-10 numbers?

**Comment by berndbischl** [comment]
@mllg 
I guess we should agree then that joining 50K lines of this should not take multiple hours....

**Comment by PhilippPro** [comment]
Whole registry.

as.dataframe is not necessary I just discovered now (as.list is necessary).
And then it is six times faster.

**Comment by berndbischl** [comment]
> as.dataframe is not necessary I just discovered now (as.list is necessary).
> And then it is six times faster.

this should then at least be in the docs, as this sounds like a VERY common mistake one could make.

**Comment by mllg** [comment]
> so you are saying that these 2 things - which where in BE, exactly for the purpose talked about here, in reduceResultsExperimentsParallel - do NOT help at all here
> 
> chunking with blocks
> parallel reduction
> ?
> 
> I really cannot believe this? Have you ever tried this?

This is intended if you apply a CPU intensive function on the results (transformation etc.). For IO it strongly depends on the file system, but you can even slow it down with too many parallel connections. 
You can easily try it yourself:

```r
library(parallel)
library(data.table)
N = 1e6
df = data.frame(x = runif(N), y = sample(letters, N, TRUE), z = rnorm(N))
write.csv(df, file = "test.csv")
system.time(for(i in 1:8) fread("test.csv"))
system.time(mclapply(1:8, function(i) fread("test.csv")))
```
I have no speedup at all. Caching on the OS side may yield wrong results as you repeatedly read the same file though.

**Comment by mllg** [comment]
@PhilippPro 
Can you post the output of `summaryRprof()` here? Would be sufficient a subset of jobs (runtime >= 2 min).

**Comment by berndbischl** [comment]
> This is intended if you apply a CPU intensive function on the results (transformation etc.

this is very certainly not true, as the reason we (= you and me) when we created the paralle-reduce-results function in BE with its tricks was basically exactly such an example @PhilippPro posted here.

and the example you posted really has nothing to do with what we are discussing here?

i am not saying anything about that it is "easy" to fix this. as we now use dt here, and the code is in general different. what i *am* saying is that we faced exactly the same problem before.

**Comment by mllg** [comment]
> and the example you posted really has nothing to do with what we are discussing here?

I was just pointing out that parallelization of IO heavy functions is often not beneficial.

**Comment by mllg** [comment]
Damn,  I just profiled it myself. You can get a huge (10x) speedup by disabling the progress bar:
```{r}
options(batchtools.progress = FALSE)
```

**Comment by mllg** [comment]
I'm down to 20s for a similar use case (named numeric(5), 50k jobs).

**Comment by PhilippPro** [comment]
prof time was 26 sec compared to 60 seconds so just half times faster approx.

**Comment by mllg** [comment]
You can also install the github version of `gaborcsardi/progress` which does not come with such a heavy overhead.

@gaborcsardi Any progress on progress?

**Comment by mllg** [comment]
Before implementing parallelization for the reduction I will wait for the next data.table which comes with built-in OpenMP support. If I'm lucky I can dodge this bullet of extra complexity.

**Comment by gaborcsardi** [comment]
@mllg: don't know, sorry, maybe a couple of weeks. Not much work, but I won't get to it until then....

**Comment by berndbischl** [comment]
> Before implementing parallelization for the reduction I will wait for the next data.table which comes with built-in OpenMP support. If I'm lucky I can dodge this bullet of extra complexity.

well, we now have completely different timings here, so i agree. 
we face seconds, not hours. 
we can (IMHO) wait until we reach a scenario where people really run into problems again.

but can we please doc the gathered knowledge from this thread in ?reduceResultsDataTable?

IMHO this could be closed then

**Comment by mllg** [comment]
Docs updated in 20bd55677362c286d5119dd1aa3790027878b069.
