### ISSUE TITLE
Get the result without create a registry folder

### ISSUE THREAD

**Issue by Idriss0peaccel** [mllg/batchtools#227]
Hello,
I would like to know how to not create a registry, i just want the result.

**Comment by mllg** [comment]
You can create the registry in a temporary folder, e.g. via
```r
makeRegistry(file.dir = tempfile())
```
R will remove this folder on exit. But note that this folder needs to be accessible by all computational nodes, so this will not work out of the box for distributed computing.

**Comment by Idriss0peaccel** [comment]
Hello, 
Thank for your help.
