### ISSUE TITLE
Execution problem

### ISSUE THREAD

**Issue by chim3y** [mllg/batchtools#247]
I would be extremely grateful for some guidance in relation to the following benchmarking. Recently, I have been trying to benchmark using batch tools for 3 learners namely rpart, logreg and random forest. For the small dataset with ids(1:208) and (209:252), it can execute but as soon as it is with ids(253:319) with training time over 3000000, the program keeps running until the 45% but doesn't go beyond that. This has been happening for the past 4 days. I cannot understand what is the main problem? I am really new to this but it will certainly mean a lot if you can kindly suggest me something. 

[Benchmark.zip](https://github.com/mllg/batchtools/files/3733934/Benchmark.zip)

**Comment by mllg** [comment]
Impossible to debug for me. I don't know what the ids are you are referring to. OML dataset ids or job ids on the local batch system? Why do you think the training time is over 3000000? Which program is running until 45% - submitJobs() or the download, or is this the progress of a single job?

Sorry, there is really nothing I can do here. You need to boil the problem down to something reproducible in a few lines of code, or need to find someone more familiar with your batch system to debug this with you.

**Comment by chim3y** [comment]
Hello sir, thank you so much for your response. I have run this program for the past 2 months and referred "https://github.com/DklRaf/Benchmark_RF-LR_OpenML". I have tried contacting the author however, I am receiving no response.

The file that I am currently mentioning in the zip file is in /benchmark folder named "benchmark-batchtools.R".  Upon executing **submitJobs(ids = 253:319, reg = regis)** , as soon as it reaches job id=286 whose mlr task id=189778 and dataid=4135, it gets struck. It neither ends the execution and nor stop it. 

45%  means the progress of the above jobs (253:319) containing around 67 jobs with the attached tasks.
[clas_time_big.xlsx](https://github.com/mllg/batchtools/files/3750212/clas_time_big.xlsx)

Any suggestions is really valuable to me.
