### ISSUE TITLE
submitjobs / max.concurrent jobs: numbers for sleeping should be options 

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#25]
currently we have these magic numbers in the code

default.wait = 5
....
wait = wait \* 1.025

while i will heavily argue that we should have very reasonable defaults here, so that most users never have to touch them, these 2 should be configurable via options.

**Comment by berndbischl** [comment]
also the waiting behavior is not documented at all in?submitJobs.

**Comment by mllg** [comment]
No priority for me, nobody I know has ever touched these in BJ/BE. PR welcome though.
