### ISSUE TITLE
on sge qstat -u $USER -s rs generates an error 

### ISSUE THREAD

**Issue by tlamadon** [mllg/batchtools#250]
adding the `rs` at the end tries to get the `rs` queue, which might not exists. This is the behavior I am getting.

**Comment by mllg** [comment]
I don't have access to a SGE system so I cannot test this. My implementation is based on the documentation which states:

```
-s {p|r|s|z|hu|ho|hs|hd|hj|ha|h|a}[+]

          Prints only jobs in the specified state,  any  combina-
          tion  of  states is possible. -s prs corresponds to the
          regular  qstat  output  without  -s  at  all.  To  show
          recently  finished  jobs, use -s z.  To display jobs in
          user/operator/system/array-dependency hold, use the  -s
          hu/ho/hs/hd  option.  The -s ha option shows jobs which
          where submitted with the qsub -a command. qstat  -s  hj
          displays  all jobs which are not eligible for execution
          unless the job has entries in the job dependency  list.
          qstat -s h is an abbreviation for qstat -s huhohshdhjha
          and qstat -s a is an abbreviation for qstat -s psr (see
          -a, -hold_jid and -hold_jid_ad options to qsub(1)).
```

So the flag `-s rs` should print only jobs with state running or suspended. Can you please double check in the terminal that the command is wrong, and maybe provide an alternative command which works for you.

**Comment by tlamadon** [comment]
Thank you for your answer, I am now thinking that the setup here might not be SGE, but perhaps Torque, however that doesn't seem t work out of the of the box either. I am going to check if I can get it to work.

**Comment by mllg** [comment]
Re-open if you have more information, closing for now.
