### ISSUE TITLE
WISH: Don't override R_FUTURE_CACHE_PATH if already set

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#253]
Would you mind updating:

https://github.com/mllg/batchtools/blob/75a5b701341c6937c779ce395fe9367dbee99c15/tests/testthat/test_future.R#L5

so that it does not override env var `R_FUTURE_CACHE_PATH` in case it is already set?  Something like:
```r
  path <- Sys.getenv("R_FUTURE_CACHE_PATH")
  if (!nzchar(path)) Sys.setenv(R_FUTURE_CACHE_PATH = fs::path(fs::path_temp(), ".future"))
```

The reason is that the current setup prevents me from running reverse dependency checks (on future.batchtools) on HPC systems where `TMPDIR` (that `fs::path_temp()` picks up) points to a local drive unique to each compute node, meaning that the batchtools registries need to be written to a different path that is accessible from all compute nodes.  So, I already set to something like `R_FUTURE_CACHE_PATH=/global/tmp/`, which unfortunately is overridden by the above.

PS. I could override `TMPDIR` temporarily but that'll be rather complicated.

**Comment by mllg** [comment]
I applied the proposed change. I'll run some tests and upload the package to CRAN.

**Comment by HenrikBengtsson** [comment]
Thanks. No need to rush it to CRAN bc of this.
