### ISSUE TITLE
Error: BatchtoolsExpiration: Future ('<none>') expired and segmentation fault

### ISSUE THREAD

**Issue by Albabune** [mllg/batchtools#263]
Hello, I am running into an error that I can't find the reason why... I have occasionally been using batchtools and future.batchtools without any issue for a couple of years and last week, when trying to use them again (on new and old notebooks) it would return me an error message. Even my old notebooks are running into issues..

I use the [sge-simple.tmpl](https://github.com/mllg/batchtools/blob/master/inst/templates/sge-simple.tmpl) template file with 2 added line for activating my conda environment before the `## Export value of DEBUGME` line:
```
. ~/.bashrc
conda activate <%= resources$conda.env %>
```
and this is how I set the resources and plan: 
```
resources <- list(h_rt = '00:10:00',
                 h_vmem = '1G', 
                 threads = '1', 
                 conda.env = "my_env",
                 conda.path = "/PATH_TO_CONDA/bin/")
plan(batchtools_sge(template = "~/.batchtools.sge.tmpl", resources=resources))
```

Test script I have been running in my jupyter notebook to see where this error comes from:
```
library('future.batchtools')
tmp %<-% { Sys.sleep(2); 3.14 }
```

The error I get (I changed the real path for `MY_PATH`):
```
Error: BatchtoolsExpiration: Future ('<none>') expired (registry path /MY_PATH/.future/20200610_170058-nejaKD/batchtools_124613705).. The last few lines of the logged output:
/var/spool/gridengine/execd/node513/job_scripts/411226: line 23: 45898 Segmentation fault      Rscript -e 'batchtools::doJobCollection("/MY_PATH/.future/20200610_170058-nejaKD/batchtools_124613705/jobs/jobaf93a159a54e2be14869997d7d67f846.rds")'
Traceback:

1. local({
 .     value <- value(future)
 .     rm(list = future_name, envir = assign.env)
 .     value
 . })
2. eval.parent(substitute(eval(quote(expr), envir)))
3. eval(expr, p)
4. eval(expr, p)
5. eval(quote({
 .     value <- value(future)
 .     rm(list = future_name, envir = assign.env)
 .     value
 . }), new.env())
6. eval(quote({
 .     value <- value(future)
 .     rm(list = future_name, envir = assign.env)
 .     value
 . }), new.env())
7. value(future)
8. value.Future(future)
9. result(future)
10. result.BatchtoolsFuture(future)
11. await(future, cleanup = FALSE)
12. await.BatchtoolsFuture(future, cleanup = FALSE)

```

If I run `batchtools::doJobCollection("/MY_PATH/.future/20200610_170058-nejaKD/batchtools_124613705/jobs/jobaf93a159a54e2be14869997d7d67f846.rds")` directly in the notebook, I get:
```
### [bt]: This is batchtools v0.9.13
### [bt]: Starting calculation of 1 jobs
### [bt]: Setting working directory to '/MY_PATH'
### [bt]: Memory measurement disabled
### [bt]: Starting job [batchtools job.id=1]
### [bt]: Setting seed to 15537 ...

### [bt]: Job terminated successfully [batchtools job.id=1]
### [bt]: Calculation finished!
```

I hope I put everything, thanks in advance for the help :)

**Comment by Albabune** [comment]
Apparently 8GB need to be provided per thread! Using the same script and templates with that much memory, it all run smoothly!

**Comment by HenrikBengtsson** [comment]
Thanks for reporting back with the solution. It might help someone else in the future.

Memory requests per job or per core is often depending on which scheduler is used and I''ve seen it cause issues when for instance moving from HPC environment to another. I certainly been hit but this too.
