### ISSUE TITLE
`batchMap()` requires named `more.args` arguments

### ISSUE THREAD

**Issue by mtmorgan** [mllg/batchtools#267]
`batchMap()` requires its `more.args` arguments to be named at https://github.com/mllg/batchtools/blob/b4b92e1806d8fe78a537a101291999807aec2764/R/batchMap.R#L65 ; this is different from `Map()` or `mapply()`, for instance, and makes it more difficult to re-use batchtools as a 'back-end' for parallel processing, e.g., https://github.com/Bioconductor/DelayedArray/issues/72 and https://github.com/Bioconductor/BiocParallel/issues/123 .

Can this constraint on `batchMap()` be relaxed?

**Comment by mllg** [comment]
I've relaxed the assertion.
