### ISSUE TITLE
Template filename for automatic lookup

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#27]
Hey, just following up on our discussion at useR about a standardized filename format for automatic lookup of template files.  My proposal is to use filenames of format:
```
.batchtools.<scheduler>.tmpl
```
Examples:

* `.batchtools.slurm.tmpl`
* `.batchtools.torque.tmpl`
* `.batchtools.sge.tmpl`
* `.batchtools.openlava.tmpl`
* `.batchtools.lsf.tmpl`

One reason for the `<scheduler>` part is that I can image projects with collaborators that work on different systems and this would provide (at least some flexibility) to provide multiple template files in the same (Git) repository.

Where should these template files be located? The default could be be to search for the _first_ available file in:

1. the current directory (`.`)
2. the user's home directory (`~`)

I'm hesitating whether it is a good thing to also fall back to a generic template file provided by the package or not.  The reason why I'm not sure is that it might be confusing and it's not clear if it will work for all schedulers and for all setups.  On the other hand, if it is possible to find a good enough template, then it's pretty neat.

**Comment by mllg** [comment]
I've implemented the config file lookup in 505dde8a4f23fb569a6e2b27ca7c3c196a4d0940. The general configuration file `batchtools.conf.R` can now also be placed in the working directory. Only the first file found is sourced. Let me know if I missed something.

> I'm hesitating whether it is a good thing to also fall back to a generic template file provided by the package or not. The reason why I'm not sure is that it might be confusing and it's not clear if it will work for all schedulers and for all setups. On the other hand, if it is possible to find a good enough template, then it's pretty neat.

This is actually super easy to implement now. But to be honest, I don't think that there is something like a minimal template that will work for most people. But I'm still undecided ...

**Comment by HenrikBengtsson** [comment]
I agree with the search algorithm and that it'll only work with the first one found (not all of them).

I was actually referring to automatic lookup of the _template_ (brew) file, not the configuration R script file.

**Comment by berndbischl** [comment]
I general, I think that the standardization discussed in the thread here is good.


> I was actually referring to automatic lookup of the template (brew) file, not the configuration R script file.

> This is actually super easy to implement now. But to be honest, I don't think that there is something like a minimal template that will work for most people. But I'm still undecided ...

Henrik, I think Michel understood what you meant (at least I would guess so).

WRT to the question whether one should fall back to a minimal / generic template:

In a certain sense we already provided those in BJ. 
https://github.com/tudo-r/BatchJobs/tree/master/examples

In every subfolder we had a "simple.tmpl" which MIGHT work on a given system.  I don't really see the hurt of falling back on this, if the user hasn't provided a custom one. Whats the worst that can happen? That it does not work. Which is exactly the same situation that you face when you dont have a template at all. If at least one is very upfront about that the user has to LIKELY update the tmpl (maybe even in the err msg when the tmp leads to a failure), that seems totally OK to me.

Also, my experience from helping people out on our mailing list, is that there is a large percentage of people who work on "simple" systems where our the simple.tmpl actually works (but of course its hard to guess statistics here).

I dont know. I would suggest if it is easy to implement this fallback, it can only help.

**Comment by mllg** [comment]
> I was actually referring to automatic lookup of the template (brew) file, not the configuration R script file.

This is also in the commit. You can place these files in the work dir / project dir / git repository and also in the home directory. I still have to update the docs on that.

**Comment by mllg** [comment]
The template is better documented now. Default templates can be placed in the template folder and are automatically used if they are named "[name].default.tmpl", but there is no such default template yet for any cluster function.





> In every subfolder we had a "simple.tmpl" which MIGHT work on a given system. I don't really see the hurt of falling back on this, if the user hasn't provided a custom one. Whats the worst that can happen? That it does not work. Which is exactly the same situation that you face when you dont have a template at all.

The error messages can be quite different. With a wrong template you might get any cryptic system error (from command not found to whatever the CLI tools return) which can be completely misleading.

**Comment by berndbischl** [comment]
> The error messages can be quite different. With a wrong template you might get any cryptic system error (from command not found to whatever the CLI tools return) which can be completely misleading.

well yeah. you are certainly correct here. its really hard for me say whether it is really worth the effort. basically one would need to test this on many systems. which we cannot.

dunno.

**Comment by HenrikBengtsson** [comment]
# Template files
My bad; now I see the code for search for templates as well.  Thanks.  Using `findConfFile()` to locate both `batchjobs.conf.R` and template files is a bit confusing (the name), but I understand it's generic enough to find "anything".  I cannot think of a better name though.

BTW, contrary to BatchJobs, you're now going with non-private filenames, i.e. no longer using a period at the beginning.  Is that to make it more explicit / visible, or is it something else (e.g. you cannot use file starting with a period in an R package)?  I don't have a strong preference for either way, but lean toward using files prefixed with a period for anything that is used for setting up / configuring local behavior and that are less likely to be shared with others, cf. `.Rprofile`, `.Renviron`, `.bashrc` etc.

# About providing a generic / default template
If doable, it's certainly lower the threshold of getting started, especially for first timers.  It would be pretty cool if a beginner can use a cluster from within R without having used a job scheduler before.  R users can now do that with multicore processing and PSOCK cluster processing, so why not also for clusters with job scheduler?

The downsides I can see is that it'll be too easy and someone by mistake launches lots of large jobs without knowing, or lots of jobs without specifying memory and wall times etc.  Another downside is that it's all "too magical" and it's never really clear to the user what the configurations are.  If there's a bit of learning curve, then it's also more likely that some thoughts go into the setup.

**Comment by mllg** [comment]
> BTW, contrary to BatchJobs, you're now going with non-private filenames, i.e. no longer using a period at the beginning. Is that to make it more explicit / visible, or is it something else (e.g. you cannot use file starting with a period in an R package)? 
> I don't have a strong preference for either way, but lean toward using files prefixed with a period for anything that is used for setting up / configuring local behavior and that are less likely to be shared with others, cf. .Rprofile, .Renviron, .bashrc etc.

In the unix world config files are mostly only "hidden" if placed in the home directory. Don't know if this is standardized, I guess I'm just used to it. If you don't like it I can change it for the first candidate (the one placed in the working directory).

> About providing a generic / default template [...]

This is now supported. As soon as someone comes up with a generic template for a scheduler, I'll add it to the package as default.

**Comment by mllg** [comment]
Closed for now. Re-open as needed.
