### ISSUE TITLE
NAMING CONVENTION: Slurm not SLURM

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#28]
I think it should be 'Slurm' not 'SLURM', cf. http://slurm.schedmd.com/ and https://en.wikipedia.org/wiki/Slurm_Workload_Manager (Wikipedia implies it was SLURM in the past).

This affects some of your function names.

**Comment by mllg** [comment]
Good point. Fixed in cdb2e949de2fdf2a1458e2ddc86a96f4a2892302.

@surmann Can you take care of the docs/template for the cluster in Dortmund? 
@ja-thomas Can you do the same for Munich?

**Comment by surmann** [comment]
I delete the file `inst/web/makeClusterFunctionsSLURM.html` because Windows is not able to distinguish between uppercase and lowercase files.
