### ISSUE TITLE
Publish 0.9.16 on CRAN

### ISSUE THREAD

**Issue by multimeric** [mllg/batchtools#287]
I'm after the two SLURM PRs that got merged in 2021 (#276, #277), but since the last CRAN release was in January that year, we don't yet have them. Would you mind publishing a new release? Thanks. 

Of course I can and will use the github master in the meantime.

**Comment by gowerc** [comment]
Just came here to say the exact same thing, would be awesome if we could get a CRAN update. Thank you for your work on this package !

**Comment by HenrikBengtsson** [comment]
Can this one be closed?
