### ISSUE TITLE
param designs: either convert factors or at least warn about them

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#32]
```
unlink("registry", recursive = T)
reg = makeExperimentRegistry()
addProblem("p1")
addAlgorithm("a1", fun = function(instance, method, ...) {
  print(str(method))
  return(method)
})

ades = data.frame(method = c("a", "b"))
addExperiments(algo.designs = list(a1 = ades))
testJob(1)
```

this shows that "method" is a factor with one element, and 2 levels. 

a) this is really nearly never what you want. you want "method" to be a string. 
for potential problems see this: 
https://github.com/mllg/checkmate/issues/75
(see the switch problem there)
NB: these are NOT the same issues. the one in cm is about guarding against this. this here is about not creating the problem in the first place, also wrt code you later dont control.
 
b) of course one can say that this is a user error, as data.frame did not set stringsAsFactors = FALSE.
but this will happen one million times, even for experienced R coders. 
although i dislike warning usually, this seems to be a clear case where a warning would be beneficial.
the other option would be to auto-convert the factor columns of the design to chars.

**Comment by mllg** [comment]
If you pass a factor, it will be treated as a factor. Switch to alternatives like tibble or data.table if you struggle with the defaults. I cannot fix R in batchtools :wink:

**Comment by berndbischl** [comment]
thanks for the extremely constructive response for an issue that 

a) costed us many wasted hour
b) took me some tome now to report
c) would take 5 min to fix
d) was handled better in BE and is now a feature downgrade

**Comment by mllg** [comment]
c) IMHO the behavior makes completely sense. If you pass a factor, it stays a factor in the design. Therefore, no fix.
d) That is not true. BE does not warn nor convert factors.
