### ISSUE TITLE
Does Batchtools work on windows ?

### ISSUE THREAD

**Issue by ShadokRaf** [mllg/batchtools#33]
Hi,

I tried to use batchtools on windows.
I get the following error launching getStatus after creating my experiment.
```
> getStatus()
Error: 'mccollect' is not an exported object from 'namespace:parallel'
```

Looking at the function mccollect, it seems not available in windows:
https://stat.ethz.ch/R-manual/R-devel/library/parallel/html/mcparallel.html

Should I use BatchExperiment instead ?

Raphael

**Comment by mllg** [comment]
Multicore is not supported for windows, but you can use `makeClusterFunctionsSocket` instead. I've added an error message for `makeClusterFunctionsMulticore` on windows in c6a0fd419edea8eee97616201e22da7c87ab32a6.

Thanks for the report.
