### ISSUE TITLE
Make batchtools easier for simple problems

### ISSUE THREAD

**Issue by jakob-r** [mllg/batchtools#37]
It's kind of a hassle to conduct easy experiments with batchtools that are more complicated than `batchMap` but kind of to simple for the algo problem differntiation.
For example if I have a static problem without parameters I still have to generate the `problem.design` list.
At the moment it kind of looks like this:
```r
for (obj.fun in obj.funs){
  addProblem(name = getID(obj.fun), data = list(obj.fun = obj.fun))
}
pdes = lapply(obj.funs, function(x) data.frame())
names(pdes) = sapply(obj.funs, getID)
```
This is kind of suboptimal to read and comprehend.

**Comment by berndbischl** [comment]
your example is incomplete and hence hard to understand. also why not make a positive suggestion how to change it then.

but to the point: you can simply leave prob.design = NULL in addExps?
this works?

```

load_all()

unlink("registry", recursive = TRUE)
makeExperimentRegistry()

for (i in 1:3){
  addProblem(name = letters[i], data = i)
}

addAlgorithm("a", fun = function(...) {
  99
})

addExperiments()

```

**Comment by jakob-r** [comment]
Okay, nvm. I don't know what I did wrong when I tried that.
