### ISSUE TITLE
Links to other packages

### ISSUE THREAD

**Issue by masalmon** [mllg/batchtools#49]
This issue is part of this [JOSS review](https://github.com/openjournals/joss-reviews/issues/135)

The README states "As a successor of the packages BatchJobs and BatchExperiments, batchtools".

* Maybe you could explain why it is a successor of those packages, e.g. what it does better? Is it meant to replace the other two packages?

* In the README of those two packages I could not find a reference to `batchtools`. It might make sense to add a link to `batchtools` in the README (and even documentation for non Github users) of `BatchJobs` and `BatchExperiments`, if `batchtools` does some tasks better?

**Comment by masalmon** [comment]
I have to correct what I have just written, I see the packages are compared in [NEWS.md](https://github.com/mllg/batchtools/blob/master/NEWS.md), sorry. But my second suggestion remains valid I think.

**Comment by masalmon** [comment]
Another thought, the doc of `batchtools` (README, vignette?) could maybe include a mention of other packages in "Parallel computing: Resource managers and batch schedulers " from https://cran.r-project.org/web/views/HighPerformanceComputing.html (`batch` and `flowr`) and compare `batchtools` to them?

**Comment by masalmon** [comment]
Similarly, in the Pi example vignette it is stated "The function batchMap(fun, ...) works analogously to Map(f, ...) of the base package.": maybe you could add a sentence about why to choose `batchMap` other `Map` (I guess the answer is that you can do more things with `batchMap`)?

**Comment by masalmon** [comment]
Is there any way to update the JSS paper to mention the new package? Or at least to add a warning in https://www.jstatsoft.org/article/view/v064i11 ?

**Comment by mllg** [comment]
I'm now mentioning the packages and the HPC task view in the readme. I can add some info to the README of BatchJobs/BatchExperiments, too. I'm unsure how to reach user not using GitHub.

@berndbischl Any thoughts on this?

**Comment by masalmon** [comment]
A not so nice way would be to have a message each time the users load BatchJobs or BadExperiments. And deprecation messages for some functions?

**Comment by mllg** [comment]
I think a call to `.Deprecated` would be too invasive because these messages are simple warnings. It would probably obscure the "regular" warnings raised if something really is not working like intended. 

A packageStartupMessage sound like a good idea to me.

**Comment by berndbischl** [comment]
> A not so nice way would be to have a message each time the users load BatchJobs or BadExperiments.

I think this is the best / most appropriate way to handle this. batchtools is a clear successor. there really is no downside to use the new package (except for minor name and API changes) , and all further development will happen in bt. 

the only reason to still use BJ and BE is to "reproduce" your old code, at least IMHO, so living with a packageStartupMessage from now on seems really OK. and in all other cases users are made aware of the new better option

**Comment by berndbischl** [comment]
@mllg 

> Maybe you could explain why it is a successor of those packages, e.g. what it does better? Is it meant to replace the other two packages?

but i think @masalmon is completely correct that it is very hard to see for new users *why* bt is better, in the README on GH and the DESC in the package. We really need to link to a little page that explains why bt is preferable (i.e. that it does not need a database and will there able to handle a) more jobs b) be a lot more robust on different systems)

what do you think?

**Comment by mllg** [comment]
Here is the packageStartupMessage: https://github.com/tudo-r/BatchJobs/commit/d2789126f2d6660cb65dc78b7c7240072007aada

I'll refactor the NEWS and put an explanation as a new section into the README.

**Comment by mllg** [comment]
I've put a short section in the README of batchtools. 

@berndbischl Can you add a link to the README of BJ/BE? I think we have done enough then to redirect users.

**Comment by mllg** [comment]
I've added links to batchtools in the respective README and as packageStartupMessage.
