### ISSUE TITLE
Organization of the reference section of the website

### ISSUE THREAD

**Issue by masalmon** [mllg/batchtools#51]
This issue is part of this [JOSS review](https://github.com/openjournals/joss-reviews/issues/135)

In the [reference](https://mllg.github.io/batchtools/reference/index.html) section of the package website, each .Rd is an entry, and there are many of them. I wonder if it would make the documentation easier to read in that part if the author used a _pkgdown.yml for creating groups, see e.g. [this one](https://github.com/dirkschumacher/ompr/blob/master/_pkgdown.yml) with the resulting [reference section](https://dirkschumacher.github.io/ompr/reference/index.html)

**Comment by masalmon** [comment]
The config file of pkgdown would also allow to change the order of the vignette, placing the Pi example on top (yep, this is a really minor comment :-) ).

**Comment by masalmon** [comment]
By the way I see the "See also" sections of the functions documentation is well used, so I guess adding groups in a config file for pkgdown wouldn't be too much work?

**Comment by mllg** [comment]
@surmann added a `_pkgdown.yml` and the function reference is now grouped.

It is not perfect, but there are some technical issues which block further customization (https://github.com/hadley/pkgdown/issues/247, https://github.com/hadley/pkgdown/issues/248). I'll keep track of the changes in pkgdown and will eventually update the grouping.

**Comment by masalmon** [comment]
Ok. The current grouping alreadly looks good :+1:

**Comment by mllg** [comment]
Thanks! I consider this then fixed for now.
