### ISSUE TITLE
JSS paper vs. JOSS paper

### ISSUE THREAD

**Issue by masalmon** [mllg/batchtools#54]
This issue is part of this [JOSS review](https://github.com/openjournals/joss-reviews/issues/135)

The JSS paper is mentioned as a resource, which is understandable. I have a few comments/questions on this:

* Is there any way to update the JSS paper to mention the new package? Or at least to add a warning in https://www.jstatsoft.org/article/view/v064i11 ?

* Could you precise more in the README what is still usable in the JSS paper (e.g. the section about " We use an ExperimentRegistry where the job definition is split into creating problems and algorithms. " according to one `batchtools` vignette) / what parts of the interfaces changed (besides having one single package now). I guess one can get this information by reading NEWS.md + the JSS paper, but NEWS.md contains other information too. This would also make the novelty of the software described in the JOSS paper clearer.

* The second paragraph of the abstract of the JSS paper is really nice (the list with letters), I wonder if it is allowed to have it in your README / in an intro vignette too.

**Comment by berndbischl** [comment]
> Is there any way to update the JSS paper to mention the new package? Or at least to add a warning in https://www.jstatsoft.org/article/view/v064i11 ?

i really dont think that we can update the paper at JSS. but we can possibly put a warning message in batchjobs and batchexps so users are made aware of batchtools, that should really be sufficient?

**Comment by masalmon** [comment]
Yes I guess it'd be sufficient, after all the JSS readers will probably try to load the 2 packages at some point or google around a bit about updates to the packages.

**Comment by berndbischl** [comment]
> Yes I guess it'd be sufficient, after all the JSS readers will probably try to load the 2 packages at some point or google around a bit about updates to the packages.

yep any interested user should at least load it :) will do that.

**Comment by mllg** [comment]
I've ported the 2nd paragraph to the README.

**Comment by mllg** [comment]
The comparison/migration stuff is now in a own vignette rather than in the news. This hopefully makes it easier to find and compare.

**Comment by masalmon** [comment]
This looks nice @mllg !

**Comment by mllg** [comment]
I guess this is now done. Please re-open if I missed something.
