### ISSUE TITLE
Flowcharts

### ISSUE THREAD

**Issue by masalmon** [mllg/batchtools#55]
This issue is part of this [JOSS review](https://github.com/openjournals/joss-reviews/issues/135)

This is again only a suggestion: the JSS paper has a flowchart for `batchExperiments`, maybe a flowchart would make sense to explain the relationships between `batchtools` function?

**Comment by berndbischl** [comment]
can you please be more precise where you would expect such a flowchart to live?
(as the JOSS paper is basically an extended abstract)

do you mean to host this online, as part of the documentation?

**Comment by masalmon** [comment]
So this is really only a suggestion and it could be in one of the vignette for instance.

**Comment by berndbischl** [comment]
ok, thats what i wanted to here. i simply wanted to clarify that you are not talking about the paper itself

**Comment by masalmon** [comment]
ok sorry for being unclear :-)
