### ISSUE TITLE
there should really me a reduceExperiments

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#57]
one really always want to have the job and algo ids in the results.

yes, one can getJobTable, reducerResultsDataTable and then join / merge the 2.
but this is a somewhat unintuitive and cumbersome for the absolute default use case

**Comment by mllg** [comment]
This is a simple `ijoin()` to combine the results:
```r
ijoin(getJobPars(), reduceResultsDataTable())
```
To be honest, I have trouble to see the necessity. With joins you have the full flexibility.

**Comment by berndbischl** [comment]
how about listening to user feedback? most people get totally stuck here. most people dont even know what a join is.

how about at least adding the MOST COMMON use case to the docs? you dont even show how to get a full result table, including params and results. 

at least an example must be in there IMHO
