### ISSUE TITLE
doJobCollection:  assertPathForOutput leads to unintuitive errors

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#61]
we discussed this on hangout

happens if:
- eg SLURM already creates empty log files on SBATCH
- you still pass the logfile path to doJobCollection in the template

apparently the latter is a user error on our part, but this was still hard to figure out and completely broke our workflow after a package update

resolution:
- check that this is really well documented
- maybe the error reporting can be made clearer
then close quickly

**Comment by mllg** [comment]
* docs improved
* assertion turned into a slave error, you should now always see it
