### ISSUE TITLE
resubmitting jobs will not remove results?

### ISSUE THREAD

**Issue by berndbischl** [mllg/batchtools#62]
hi,

(sorry, i can try to post a reprod. ex. later, ping me if i forget and you need this)

i you resubmit a job, do you ENSURE that you remove all status info in the project dir and so on?
in other words: do you completely reset the job?

because if you dont do that you can run into inconsistent registry states, which is REALLY NOT what you want

if i get it correctly this happened to us:
we had a job, which already had a result. the job was apparently resubmitted. the 2nd time it failed (stochastic error?). now the job results was present on disk (with an older date than the log), but the state in the reg was "error".
in conculsion: if i collect my job results, i now have an old outdated one, but the job state says its an "error". that seems really bad?

**Comment by mllg** [comment]
Here is the "reset" in submitJobs:
https://github.com/mllg/batchtools/blob/master/R/submitJobs.R#L169

I do not delete the result file itself, but update the state.

If I understand you correctly, the database holds the correct state. But I should double check to (a) delete old results or (b) ensure that I do not allow to collect these results with `loadResult`, `reduceResults`, etc.?

**Comment by berndbischl** [comment]
> Here is the "reset" in submitJobs:
> https://github.com/mllg/batchtools/blob/master/R/submitJobs.R#L169
> 
> I do not delete the result file itself, but update the state.

yes, but that's simply the "computational state" update (as you also said).
and that was fine for me, but see c) below.

a) I would really encapsulate that "reset" in submitJobs in a conceptual function call.
you already have resetJobs for this. 

b) and i think you have to also delete the files. because, as i just experienced, NOT doing this seems 
to be too error-prone.

c) it also seems really worrysome that the state in my case seemed to have been correct ("error") but I could STILL retrieve a result from disk. I mean that seems like to problems: the files is there (what i am complaining here) but also that you don't check the state of the jobs whose results I ask about? 
shouldnt bt COMPLAIN when I ask about results ob faulty jobs?

> If I understand you correctly, the database holds the correct state. 

yes

> But I should double check to (a) delete old results or (b) ensure that I do not allow to 
> collect these results with loadResult, reduceResults, etc.?

yes

**Comment by berndbischl** [comment]
w.r.t. file deletions: it is more. delete all files, including logs, scripts etc

**Comment by mllg** [comment]
Old result files are now deleted on submit. `sweepRegistry` also deletes all result files for jobs which are not terminated. 

Logs do not have to be removed immediately, they use a unique identifier in the file name, so there is no mix up possible (and they are automatically removed by `sweepRegistry`). Scripts are created in a temp directory and R handles their deletion.

To properly implement array jobs, I'll have to touch the file name scheme anyway in the next weeks. I will probably use the job hash in every file name which should make errors like this very unlikely in the future. Reopen if you spot something I missed.
