### ISSUE TITLE
Simple torque tmpl?

### ISSUE THREAD

**Issue by jgrn307** [mllg/batchtools#72]
Hi there -- I'm having a hard time getting working with "tmpl" files on a Torque -- is there an example of a simple.tmpl that works with batchtools?  When I use simple.tmpl from BatchJobs (https://raw.githubusercontent.com/tudo-r/BatchJobs/master/examples/cfTorque/simple.tmpl) I run into a bunch of errors: 

Submitting 10 jobs in 10 chunks using cluster functions 'Torque' ...
Error in cat(job.name) : object 'job.name' not found
Error in cfBrewTemplate(reg, template, jc) :
  Error brewing template: Error in cat(job.name) : object 'job.name' not found

When I use torque_lido.tmpl I get:
Submitting 10 jobs in 10 chunks using cluster functions 'Torque' ...
Error in submitJobs(reg = reg, resources = list(walltime = 3600)) :
  Assertion on 'resources$memory' failed: Must be of type 'single integerish value', not 'NULL'.
Error in cfBrewTemplate(reg, template, jc) :
  Error brewing template: Error in submitJobs(reg = reg, resources = list(walltime = 3600)) :
  Assertion on 'resources$memory' failed: Must be of type 'single integerish value', not 'NULL'.

Any ideas?

**Comment by mllg** [comment]
Hi,

Here are two templates which should work:

* https://github.com/mllg/batchtools/blob/master/inst/templates/slurm_simple.tmpl (example)
* https://github.com/mllg/batchtools/blob/master/inst/templates/slurm_dortmund.tmpl (works on my computing site)

Does that help?

**Comment by mllg** [comment]
Oh, these are for the devel version and eventually do not work with the CRAN version. I'll update the CRAN version this week.

**Comment by HenrikBengtsson** [comment]
This is a TORQUE template that I've used during my alpha testing of batchtools:
```sh
#!/bin/bash
######################################################################
# A batchtools launch script template for a Torque/PBS
#
# Author: Henrik Bengtsson 
######################################################################

## Job name:
#PBS -N <%= job.hash %>

## Direct streams to logfile:
#PBS -o <%= log.file %>

## Merge standard error and output:
#PBS -j oe

## Email on abort (a) and termination (e), but not when starting (b)
#PBS -m ae

## Resources needed:
<% if (length(resources) > 0) {
  opts <- unlist(resources, use.names = TRUE)
  opts <- sprintf("%s=%s", names(opts), opts)
  opts <- paste(opts, collapse = ",") %>
#PBS -l <%= opts %>
<% } %>

## Launch R and evaluated the batchtools R job
Rscript -e 'batchtools::doJobCollection("<%= uri %>")'
```

**Comment by mllg** [comment]
Package has been updated. Let me know if you need further assistance.
