### ISSUE TITLE
Porting to batchtools: BatchJobs::removeRegistry()?

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#78]
What's the corresponding `batchtools` function to `BatchJobs::removeRegistry()`?  Something for cleaning out any permanent / intermediate files from the file system.

If my question make sense, I think this could be helpful to add to Section 'Porting to batchtools' in the 'Migration from BatchJobs/BatchExperiments' vignette.

**Comment by mllg** [comment]
I simply forgot about this one. Now in batchtools, with a mention to `sweepRegistry`.
