### ISSUE TITLE
DOCUMENTATION: Mention `job.hash` (was `job.name`)

### ISSUE THREAD

**Issue by HenrikBengtsson** [mllg/batchtools#94]
The ['Migrating from BatchJobs/BatchExperiments' vignette](https://github.com/mllg/batchtools/blob/master/vignettes/v01_Migration.Rmd), seems to be missing information on the renaming of `job.name` to `job.hash` that is used in the template files.

For instance, with BatchJobs, you would use the following for a TORQUE / PBS template file:
```sh
#PBS -N <%= job.name %>
```
whereas with batchtools that doesn't work but you need to use:
```sh
#PBS -N <%= job.hash %>
```

**Comment by mllg** [comment]
Thanks, should be better covered now.

**Comment by HenrikBengtsson** [comment]
Looks good; the reference to JobCollection is also very useful - I didn't know I could use those fields in the template.
